### ISSUE TITLE
Map should use lat long instead of address

### ISSUE THREAD

**Issue by James-A-White** [James-A-White/HarrierCentral#165]

**Comment by diabWH3** [comment]
I've noticed that sometimes the map shows the correct location (lat/long probably?), but then it feeds a different location to Google Maps when I use that to drive to the hash. Maybe it's sending the location/Point of Interest info to the Google Maps application instead of the lat/long coordinates? I see this happen more often when the event is created automatically from Facebook.

**Comment by James-A-White** [comment]
Fixed in 1.0.36
