### ISSUE TITLE
Add map interface to show run locations

### ISSUE THREAD

**Issue by James-A-White** [James-A-White/HarrierCentral#19]
Add a map interface to show run locations.

**Comment by James-A-White** [comment]
The mobile app and web admin app have been updated to support a map feature showing runs. Kennels can select the color to be used for their pins in using the Kennel editor in HcWeb. Runs will then be displayed using these colors in the app on the map display.

The map can be filtered to show:

- All runs
- Recent runs (runs within the past 90 days plus all future runs)
- All past runs
- All future runs
- All runs that were attended by the user of the app
- All runs that were hared by the user of the app

This feature will be available in the 0.8.150 release

**Comment by James-A-White** [comment]
... also added markers to show the location of kennels on the map as well.

Kennels aggregate into clusters with a purple label and runs aggregate into clusters with a blue label.

**Comment by modderkabouter** [comment]
Map works good here. Just some thoughts:
- location button would be nice
- here maybe check what happens when you have location off, en then enable it while the app is running (but make sure to be somewhere else). Does it update automatically?  But here the button mentioned before might do the trick.
- default view on the map on future runs (so the map doesn't get too cluttered after a couple of months/years)
- Map layout: might be nice to have a layout where you can identify green bits like forests etc. (for example openstreetmap)

**Comment by James-A-White** [comment]
Finished. May implement some of the suggestions above in a future version.
