### ISSUE TITLE
HC-Web, Bug: hashruns.org iframe embed broken

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#289]
Seattle's website, www.wh3.org, has an embedded iframe supposed to show all Washington, USA runs, but it now shows an empty dataset:
`<iframe class="embed-responsive-item" src="https://www.hashruns.org/#/RD?regionNames=washington"></iframe>`

![image](https://user-images.githubusercontent.com/49632769/157366261-3451c5e4-c3fc-423e-9a48-047d49305d04.png)

**Comment by James-A-White** [comment]
Sorry, I just saw this.  I think the issue was caused when we changed the way we dealt with Kennels and how they display runs on HashRuns.org.  Originally, we were posting all runs there, now we have changed it to an "opt in" approach. When we did this, we turned all Kennels "off" and then requested those that wanted to be on HashRuns.org to let us know. I've checked your site and it seems to be working for your Kennels now. In the future if you have a Kennel you want to appear here, just have an admin contact us and we'll enable that feature.

Thanks and sorry it took so long for me to get around to this.

**Comment by diabWH3** [comment]
No problem! I saw it wasn't "broken" for long, so figured you had a handle
on things. I appreciate the hard work!

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*
