### ISSUE TITLE
URGENT: Cannot see any Upcoming Runs and some other membership issues

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#316]
Without intentionally doing anything to or with the app, I can no longer see any info on my Upcoming Runs screen. I updated my app and refreshed the cache using the in-app option, to no avail. Even a phone restart does not fix the issue.
Without being able to see upcoming runs, I cannot manage the trail attendance for current or upcoming events.

![Screenshot_20220523-103548](https://user-images.githubusercontent.com/49632769/169876143-cf923d94-9a04-400f-a8ed-8658e0c31371.png)
![Screenshot_20220523-103257](https://user-images.githubusercontent.com/49632769/169876146-f1354838-edda-4054-bad0-1cb9c54aafdb.png)

**Comment by diabWH3** [comment]
This issue was repeatable with every member of the kennel at last night's SeaMon trail, activated by refreshing (pull-to-refresh motion) their Upcoming Runs list. However, this morning I can see all upcoming runs, so the system seems to be working? I'll close the ticket for now.

**Comment by James-A-White** [comment]
Hey DIAB, what happened is that some bad data got imported from our custom integration with San Diego. More specifically it was a Unicode "braille" character 0x2028. This caused the JSON parsing in the app to fail, which resulted in runs not being available. It happened while I was at work and it took a few hours for me to address it after getting home. I've put in a temporary mitigation, but need a better long term strategy for filtering out bad unicode characters - it's not simple because the Asian Kennels heavily use Unicode. I've been looking for a list of characters that will break the JSON parser, but to this point only have discovered two through our custom integration mechanism 0x2029 and 0x2028.

Sorry for the disruption in service!

**Comment by diabWH3** [comment]
Thanks for the update! I am not jealous of your efforts to accommodate
world-wide app adoption while troubleshooting all the new use cases that
uncovers.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*
