### ISSUE TITLE
https://portal.harriercentral.com/ makes me use my phone.

### ISSUE THREAD

**Issue by mcr** [James-A-White/HarrierCentral#318]
When I visit with my browser (not phone), I just get a QR code for my phone, which isn't anyplace near me.
I first noticed this at: https://ah3.nl/index.php/upcoming-and-specials/

**Comment by James-A-White** [comment]
Two things: First, this is a problem with the URL used by the admin to embed the content... I'll get with him to fix it.

Second, for DIAB: Did you know you can change the background and foreground colors of the content to match your website?  ;-)

**Comment by diabWH3** [comment]
> Second, for DIAB: Did you know you can change the background and foreground colors of the content to match your website? ;-)

I did not know that! What's the secret code for that?

**Comment by James-A-White** [comment]
Hey DIAB, you can extend the URL with these parameters:

&backgroundColor=F5D293&textTheme=dark

depending on he background color, you will have to choose either a light or dark text theme.

You can use this website to select a HEX color if you don't have another way to do it.

https://imagecolorpicker.com/en

Here's a URL fully formed.

https://www.hashruns.org/#/RD?regionNames=washington,maine&backgroundColor=F5D293&textTheme=dark

I'm going to close this because the original website referenced had used the wrong URL.

If you have any questions about the URLs let me know.
