### ISSUE TITLE
HC-App: Auto show runs not working, some kennels/runs not showing

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#321]
Installed new Android v. 1.1.0 and the "Auto show runs" page does not show some placeholder events a local kennel has put on there. 
My view is set up for "auto show runs 100 miles" but I cannot see any ucpoming Tacoma H3 or SSH3 (South Sound H3) runs. Most of their listed events are placeholders and do not have location data populated, but even the one that does ([SSH3 #192](https://psav.sharepoint.com/:li:/s/NationalRepairTeam/E__aV_hVCTNGjnI6TBgKBtYBWps9iMPmp232xmQdOuVdBA?e=s52bhI)) Does not show on my dashboard except in the "All other upcoming runs" list.

**Comment by diabWH3** [comment]
![Screenshot_20220627-141028](https://user-images.githubusercontent.com/49632769/176036241-fca1506a-fa2e-4f23-887e-606f1d69fa4b.png)

![Screenshot_20220627-141006](https://user-images.githubusercontent.com/49632769/176036245-8f1f0ef8-ac3e-46ea-a7be-72e4cfc0f2f2.png)

**Comment by diabWH3** [comment]
Makes sense to me! I think that enhancement would be nice so local kennels
show up in the auto filtered view. Thanks!

**Comment by James-A-White** [comment]
Fixed in 1.1.1

Made a change to use the Kennel's lat/lon (or the Kennel's city's lat/lon) to determine where in the list the run should appear if no location has been assigned.  I also now display "No location provided" in the run tile to be more explicit when a run or placeholder has been added without a location.  Good suggestion DIAB, I think this is much more intuitive now.
