### ISSUE TITLE
Bug: Map location shown doesn't load correctly in Google Maps app

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#69]
The screenshots below show that the map preview does not translate into a correct Google Maps link. This is an event that auto populated from Facebook, so I wonder how the data is shown from that platform and is translated into Harrier Central.

![Screenshot_20210822-173104](https://user-images.githubusercontent.com/49632769/130375478-82218210-cb49-4f18-96c0-15ce8dd9ea0e.png)

![Screenshot_20210822-173119](https://user-images.githubusercontent.com/49632769/130375482-a40aad91-c085-4ae1-ad32-02020093ee88.png)

**Comment by James-A-White** [comment]
Can you tell me which event it was?  One of the problems with Facebook is that I don't get Lat/Longs if the location given is not a part of their an official "place" in their database, so I have to take the location information that it does give me and run it through a third-party (Microsoft) gazetteer API... the hope is that this API correctly translates the location ... which it will if there is a street name and zip code. Otherwise, the location can be incorrect.  

Which event is this? I can play with it a bit more and see if I can fine tune the Gazetteer API from MS.

Also, you should be able to manually set the location from within the App now using the Edit Event button if the Facebook import does not work correctly.

Thx!

James

**Comment by diabWH3** [comment]
It was for SeaMon H3 #308, but the hare has since updated the info on FB,
which pushed to the app and now works correctly. I agree that the FB Point
of Interest database is crappy and makes things unnecessarily
difficult...but at least they've implemented a drag-and-drop pin feature to
help with non-POI locations.

The issue I experienced is that the HC app guessed the location correctly
when displaying a map on the event details screen, but when I clicked the
pin, it didn't send that pin-drop location to Google Maps. Instead, Google
Maps just received the city/state/zip and sent me results for the entire
city limits.

If I find this error again, hopefully it won't be the night before trail so
we don't have to "fix" it right away and can properly document the bug. :)

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*

**Comment by diabWH3** [comment]
Also, this is VERY likely just a case of "garbage in, garbage out" due to
the inflexibility of Facebook's location selector.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*

**Comment by diabWH3** [comment]
Happened again with SeaMon H3 #311. This time, I think FB has the correct start location info and the in-app map looks correct. When I click the map and it loads into Google Maps, it selects the center of the country.

![Screenshot_20210913-173844](https://user-images.githubusercontent.com/49632769/133175180-d5ba943c-ef4d-4317-a58f-8cef1ddbc8d1.png)

![Screenshot_20210913-173855](https://user-images.githubusercontent.com/49632769/133175190-a38b0754-f8dc-498c-bafd-84fc32a91647.png)

**Comment by James-A-White** [comment]
Fixed in 1.0.40

I've changed this... When Google Maps is launched from the app, I send only the lat/long and not the text address. This should fix the issue. Please keep an eye out and let me know if you have any more issues with launching Google maps from the app.
