### ISSUE TITLE
Enhancement: Improve User Experience with Hash Cash credit

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#79]
Currently, it doesn't appear that there is good visibility for when a user has "credit" with a kennel (leftover money from a previous over-payment). From what I can tell, the only way to view this from the admin view is by sending out a trail's Hash Cash report or by accessing the HC-Web admin portal.

It would be helpful to make some improvements to make it more obvious, both to the hasher with credit to use and to the kennel admin needing to track said credit. These could include:
 - A prompt for the user to use their credit when RSVPing to a hash (similar to the Paypal/e-payment buttons)
 - Somewhere for the user to check all current kennel credits in one spot; maybe their profile page or 
 - Credit balance info on the Manual Check-In page when selecting a hasher's payment method.

Just a couple ideas, but maybe there are better options, depending on how that info is calculated and wherever there might be some available real estate in the app.

**Comment by James-A-White** [comment]
Actually, this already works... see attached screenshot. This is what you would see when checking in to the next run. Notice that the credit button has a "(Credit: $5.00)" listed. This means that the Hasher has $5.00 in credit remaining.  I might need to find a better word to put instead of "Credit", but it has to be short to fit in the UI. Any thoughts?

![image](https://user-images.githubusercontent.com/5836474/131682238-2920df95-183d-4ac7-86d6-ab4275fe55bd.png)

**Comment by diabWH3** [comment]
Good to know this functions properly when trying to check-in at the next
run!
For the admin interface, here's a suggested change to make the option and
current balance more easy to differentiate:
[image: image.png]

On the end-user side, is there an easy place for them to see their current
credit with any given kennel? Maybe on each kennel's information screen? Or
maybe just a prompt alongside each trail's sign-in/payment pop-up?

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*
