### ISSUE TITLE
Error, HC-App: Runner payment credit -> display issues

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#80]
Starting this ticket on desktop and will follow up on mobile with screenshots.

Screenshots below show an intentional overpayment by Cougar Rican at SeaMon H3 #309 last night. Trail cost was $5, but he paid $10 to test how the system tracks a user's credit for future runs.

- When doing manual attendance as Hash Cash, the "Pay Other" pop-up dialog allows you to input a custom payment amount, but does not show that amount when you click the "Pay Other" button again in the future; it only shows a blank entry field. I would expect this to show a value if one already exists.
- In the "Hash Cash" admin view, the custom payment amount does not display. I would expect this to say "$10.00"
- The Hash Cash Report email shows the correct custom payment, but does not reflect the increase in user's credit towards future runs.

This is associated with enhancements requested in #79

**Comment by diabWH3** [comment]
![Screenshot_20210831-093520](https://user-images.githubusercontent.com/49632769/131553569-7f1cc659-1f07-49f9-af00-750dd391a9bc.png)
![Screenshot_20210831-093249](https://user-images.githubusercontent.com/49632769/131553573-dd32c66f-14de-4604-ad9c-8d3d5b818ca4.png)
![Screenshot_20210831-110354](https://user-images.githubusercontent.com/49632769/131553575-56c307d7-bd81-4bcb-8bbb-cc42ba593d90.png)

**Comment by James-A-White** [comment]
_When doing manual attendance as Hash Cash, the "Pay Other" pop-up dialog allows you to input a custom payment amount, but does not show that amount when you click the "Pay Other" button again in the future; it only shows a blank entry field. I would expect this to show a value if one already exists._

This is by design. When people pay more (or less) than they should it does not mean that's what they would pay each time. I could keep a default value there, but it might be confusing to people using the app to think that the other amount to be paid has to be that value. Let me think about this.

_In the "Hash Cash" admin view, the custom payment amount does not display. I would expect this to say "$10.00"_

This is a configuration issue. In your Kennel admin on the portal there was a "$" indicated as the currency symbol. Actually, it should have either been left blank or been "$^".  The numeric value gets inserted where the "^" symbol is. The reason for this is that some currencies place the number after the currency symbol and some place it before the currency symbol. For example, in English Canada, the dollar symbol goes to the left of the amount, while in French Canada, the dollar sign goes to the right. I've updated your Kennel and removed the $ and this feature is now working properly because the proper default value is being used based on the country you are located in.

The report has been fixed. Thanks for picking that one up!
